# Generated by Django 4.2.20 on 2025-04-30 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChallengeInquiry',
        ),
    ]
