# Generated by Django 4.2.20 on 2025-04-30 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_delete_challengeinquiry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='challenge',
            name='tags',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
